language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "6"
  - "node"
  - "4.1"
  - "4.0"
  - "0.12"

# The following are currently not supported:
#  - "0.10"
#  - "0.8"
#  - "0.6"

notifications:
  email: false
before_install:
  - npm i -g npm@^3.0.0
  - npm i
before_script:
  - npm prune
script:
  - npm test
